//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityAttribute
    {
        public int ActivityAttributeId { get; set; }
        public int ActivityId { get; set; }
        public string ActivityAttributeName { get; set; }
        public string ActivityAttributeValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ClientId { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
