//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgedCampaign
    {
        public int CAMPAIGN_ID { get; set; }
        public Nullable<int> MinAgeDays { get; set; }
        public Nullable<int> MaxAgeDays { get; set; }
        public string SelectionClause { get; set; }
        public string ExlcudeClause { get; set; }
        public string Priority { get; set; }
        public Nullable<int> DailyCap { get; set; }
    }
}
