//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class APITestLead
    {
        public long LEAD_ID { get; set; }
        public string URL_ID { get; set; }
        public string AD_ID { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public string phone_number { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string postal_code { get; set; }
        public string IP_address { get; set; }
        public string URLREFERER { get; set; }
        public string TRUSTED_FORM_CERT { get; set; }
    }
}
