//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserGroup
    {
        public int ApplicationUserGroupId { get; set; }
        public string ApplicationUserId { get; set; }
        public string ApplicationGroupId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
    
        public virtual ApplicationGroup ApplicationGroup { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
