//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignOutput
    {
        public int CampaignOutputId { get; set; }
        public string Name { get; set; }
        public string HttpMethod { get; set; }
        public string UrlDestination { get; set; }
        public string HttpHeadersJson { get; set; }
        public string UrlParametersJson { get; set; }
        public string HttpBody { get; set; }
        public string ContentType { get; set; }
        public string StatusMapping { get; set; }
    }
}
