//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignLimit
    {
        public int CAMPAIGN_ID { get; set; }
        public Nullable<int> Overall_Limit { get; set; }
        public Nullable<int> Yearly_Limit { get; set; }
        public Nullable<int> Monthly_Limit { get; set; }
        public Nullable<int> Daily_Limit { get; set; }
        public Nullable<int> Hour_Limit { get; set; }
        public Nullable<int> HalfHour_Limit { get; set; }
        public Nullable<int> QuarterHour_Limit { get; set; }
        public Nullable<int> Minute_Limit { get; set; }
        public Nullable<System.TimeSpan> SundayStart { get; set; }
        public Nullable<System.TimeSpan> SundayEnd { get; set; }
        public Nullable<System.TimeSpan> MondatStart { get; set; }
        public Nullable<System.TimeSpan> MondayEnd { get; set; }
        public Nullable<System.TimeSpan> TuesdayStart { get; set; }
        public Nullable<System.TimeSpan> TuesdayEnd { get; set; }
        public Nullable<System.TimeSpan> WednesdayStart { get; set; }
        public Nullable<System.TimeSpan> WednesdayEnd { get; set; }
        public Nullable<System.TimeSpan> ThursdayStart { get; set; }
        public Nullable<System.TimeSpan> ThursdayEnd { get; set; }
        public Nullable<System.TimeSpan> FridayStart { get; set; }
        public Nullable<System.TimeSpan> FridayEnd { get; set; }
        public Nullable<System.TimeSpan> SaturdayStart { get; set; }
        public Nullable<System.TimeSpan> SaturdayEnd { get; set; }
    }
}
