//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGN
    {
        public int CAMPAIGN_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public string NAME { get; set; }
        public string KEY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<int> CampaignOutputId { get; set; }
        public Nullable<decimal> LeadPrice { get; set; }
        public Nullable<bool> AgedLeads { get; set; }
        public Nullable<int> ContractMinDays { get; set; }
        public Nullable<int> ContractMaxDays { get; set; }
        public Nullable<int> ReachMinimum { get; set; }
    }
}
