//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignOutputSendLog
    {
        public long CONTACT_ID { get; set; }
        public int Campaign_ID { get; set; }
        public int CampaignOutputId { get; set; }
        public Nullable<int> ResponseStatusCode { get; set; }
        public string ResponseReasonPhrase { get; set; }
        public string ResponseBody { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
