//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignDetail
    {
        public int CLIENT_ID { get; set; }
        public string NAME { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<decimal> LeadPrice { get; set; }
        public Nullable<bool> AgedLeads { get; set; }
        public Nullable<int> CampaignOutputId { get; set; }
        public string Expr1 { get; set; }
        public bool Expr2 { get; set; }
    }
}
