//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public int CLIENT_ID { get; set; }
        public string NAME { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string WEBSITE { get; set; }
        public string INVOICECONTACT { get; set; }
        public string INVOICEEMAIL { get; set; }
        public string INVOICEPHONE { get; set; }
        public string LEGALNAME { get; set; }
        public string LEGALADDRESS { get; set; }
        public string LEGALADDRESSCITY { get; set; }
        public string PLATFORMURL { get; set; }
        public string PLATFORMUSERNAME { get; set; }
        public string PLATFORMPASSWORD { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
        public bool ACTIVE { get; set; }
    }
}
