//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRecordDetail
    {
        public int ContactRecordDetailId { get; set; }
        public int ContactId { get; set; }
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public string QuestionResponseText { get; set; }
        public string QuestionResponseValue { get; set; }
        public string QuestionKeys { get; set; }
    
        public virtual ContactRecord ContactRecord { get; set; }
    }
}
