//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotactRecord_temp
    {
        public int ContactID { get; set; }
        public string ClientCallID { get; set; }
        public string ANI { get; set; }
        public Nullable<System.DateTime> CallStartDateTime { get; set; }
        public Nullable<System.DateTime> CallEndDateTime { get; set; }
        public string CallState { get; set; }
        public string DispositionCode { get; set; }
        public string ProjectName { get; set; }
        public string LeadRecordId { get; set; }
        public string Notes { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserId { get; set; }
        public string ClientID { get; set; }
    }
}
