//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBadset
    {
        public int FBadsetID { get; set; }
        public string FBadsetName { get; set; }
        public Nullable<int> FBcampaignID { get; set; }
    }
}
