//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBImpressionData
    {
        public string Ad_Name { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public int Impressions { get; set; }
        public double Amount_Spent { get; set; }
        public int Link_Clicks { get; set; }
    }
}
