//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDRServiceQueue
    {
        public int IDRServiceQueueId { get; set; }
        public int ContactId { get; set; }
        public string ClientCallId { get; set; }
        public string ServiceQueue { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ClientId { get; set; }
    
        public virtual ContactRecord ContactRecord { get; set; }
    }
}
