//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadRecord()
        {
            this.LeadRecordAttributes = new HashSet<LeadRecordAttribute>();
        }
    
        public string LeadRecordId { get; set; }
        public string CustomId { get; set; }
        public string LeadOwner { get; set; }
        public string LeadStatus { get; set; }
        public string LeadSource { get; set; }
        public string LeadRating { get; set; }
        public string LeadType { get; set; }
        public string ProcessState { get; set; }
        public string Company { get; set; }
        public string Industry { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string AltEmail { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> PotRevenue { get; set; }
        public string InterestIn { get; set; }
        public Nullable<bool> DNS { get; set; }
        public Nullable<bool> DNC { get; set; }
        public Nullable<bool> DNM { get; set; }
        public string TimeZone { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ClientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadRecordAttribute> LeadRecordAttributes { get; set; }
    }
}
