//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadRecordAttribute
    {
        public int LeadRecordAttributeId { get; set; }
        public string LeadRecordId { get; set; }
        public string LeadAttributeName { get; set; }
        public string LeadAttributeValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ClientId { get; set; }
    
        public virtual LeadRecord LeadRecord { get; set; }
    }
}
