//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadLookupDetail
    {
        public int LeadLookupDetailId { get; set; }
        public int LeadLookupId { get; set; }
        public string LookupText { get; set; }
        public string LookupValue { get; set; }
    
        public virtual LeadLookup LeadLookup { get; set; }
    }
}
