//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEADS_ATTRIBUTE
    {
        public long LEAD_ATTRIBUTE_ID { get; set; }
        public long LEAD_ID { get; set; }
        public string ATTRIBUTE_NAME { get; set; }
        public string ATTRIBUTE_VALUE { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
    }
}
