//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class leads_data
    {
        public Nullable<int> C_lead_id_ { get; set; }
        public string C_url_id_ { get; set; }
        public Nullable<int> C_ad_id_ { get; set; }
        public string C_gender_ { get; set; }
        public Nullable<System.DateTime> C_dateOfBirth_ { get; set; }
        public string C_email_ { get; set; }
        public string C_phoneNumber_ { get; set; }
        public string C_firstName_ { get; set; }
        public string C_lastName_ { get; set; }
        public string C_address_ { get; set; }
        public string C_postalCode_ { get; set; }
        public string C_ip_ { get; set; }
        public string C_urlReferer_ { get; set; }
        public System.DateTime C_createdAt_ { get; set; }
    }
}
