//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string SiteNo { get; set; }
        public string CustomerNumber { get; set; }
        public string SiteName { get; set; }
        public string SiteAddressOne { get; set; }
        public string SiteAddressTwo { get; set; }
        public string SiteCity { get; set; }
        public string SiteState { get; set; }
        public string SiteZipCode { get; set; }
        public string SitePhone { get; set; }
        public string SpecialInstructions { get; set; }
        public string SiteCustomerStoreCode { get; set; }
        public string SiteDesc { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
