//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public string ErrorShortDescription { get; set; }
        public string ExceptionType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string MethodName { get; set; }
        public string ClassName { get; set; }
        public string ImpactLevel { get; set; }
        public string ApplicationName { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public string InnerException { get; set; }
        public string InnerExceptionMessage { get; set; }
        public string IpAddress { get; set; }
        public string CallDetail { get; set; }
        public string UserId { get; set; }
        public string ClientId { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
