//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputSegment
    {
        public int OUTPUT_SEGMENT_ID { get; set; }
        public string OUTPUT_SegmentName { get; set; }
        public string OUTPUT_SegmentDesc { get; set; }
        public string OUTPUT_SegmentJSON { get; set; }
    }
}
