//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PixelTracking
    {
        public long PixelTrackingID { get; set; }
        public string PixelUser { get; set; }
        public string PixelSource { get; set; }
        public string PixelDetail { get; set; }
        public Nullable<System.DateTime> PixelTimeStamp { get; set; }
    }
}
