//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVENUE
    {
        public int CLIENT_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public Nullable<decimal> REVENUE1 { get; set; }
        public Nullable<int> VOLUME { get; set; }
        public Nullable<System.DateTime> MONTH { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string INVOICE_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
    }
}
