//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptItemSelector
    {
        public int ScriptItemSelectorID { get; set; }
        public string SelectorDesc { get; set; }
        public string SelectorTitle { get; set; }
        public string ItemList { get; set; }
        public string LayoutType { get; set; }
        public string FilterKeys { get; set; }
        public string SetKeys { get; set; }
        public string DisplayColumns { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    }
}
