//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptVariableDetail
    {
        public int ScriptVariableDetailID { get; set; }
        public int ScriptVariableID { get; set; }
        public int ScriptClauseID { get; set; }
        public int ShowIf { get; set; }
        public string Value { get; set; }
        public int Sequence { get; set; }
    
        public virtual ScriptClause ScriptClause { get; set; }
        public virtual ScriptVariable ScriptVariable { get; set; }
    }
}
