//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptLink
    {
        public int ScriptLinkID { get; set; }
        public string LinkDesc { get; set; }
        public string LinkDisplay { get; set; }
        public string LinkType { get; set; }
        public string LinkURL { get; set; }
        public Nullable<int> LinkTypeID { get; set; }
        public bool LinkNewWindow { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    }
}
