//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptQuestionareDetail
    {
        public int ScriptQuestionareDetailID { get; set; }
        public int ScriptQuestionareID { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<int> ScriptQuestionID { get; set; }
        public Nullable<int> ShowWhen { get; set; }
        public Nullable<int> Showif { get; set; }
    
        public virtual ScriptQuestion ScriptQuestion { get; set; }
        public virtual ScriptQuestionare ScriptQuestionare { get; set; }
    }
}
