//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptSectionLayout
    {
        public int ScriptSectionLayoutID { get; set; }
        public int ScriptSectionID { get; set; }
        public int Sequence { get; set; }
        public int ElementID { get; set; }
        public string ElementType { get; set; }
        public Nullable<int> ShowWhen { get; set; }
        public Nullable<int> ShowIf { get; set; }
        public string ContainerWidth { get; set; }
        public string TemplateDivID { get; set; }
    
        public virtual ScriptSection ScriptSection { get; set; }
    }
}
