//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptDataView
    {
        public int ScriptDataViewID { get; set; }
        public string DataViewDesc { get; set; }
        public string DataViewType { get; set; }
        public string DataViewSource { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    }
}
