//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScriptProject()
        {
            this.ScriptProjectVariables = new HashSet<ScriptProjectVariable>();
            this.ScriptProjectWorkflows = new HashSet<ScriptProjectWorkflow>();
        }
    
        public int ScriptProjectID { get; set; }
        public string ProjectDesc { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<bool> RequireKey { get; set; }
        public Nullable<System.Guid> KeyText { get; set; }
        public Nullable<int> LogoImageID { get; set; }
        public Nullable<int> ScriptMenuID { get; set; }
        public string ScreenSize { get; set; }
        public string ScreenLayout { get; set; }
        public Nullable<bool> ShowWorkflowSection { get; set; }
        public Nullable<bool> ShowLead { get; set; }
        public Nullable<bool> ShowNotes { get; set; }
        public Nullable<bool> ShowCallback { get; set; }
        public Nullable<bool> ShowLanguage { get; set; }
        public Nullable<bool> ShowNotification { get; set; }
        public string NotificationText { get; set; }
        public string Parameter { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    
        public virtual ScriptImage ScriptImage { get; set; }
        public virtual ScriptMenu ScriptMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScriptProjectVariable> ScriptProjectVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScriptProjectWorkflow> ScriptProjectWorkflows { get; set; }
    }
}
