//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptDash
    {
        public int ScriptDashID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> RequireKey { get; set; }
        public Nullable<System.Guid> KeyText { get; set; }
        public Nullable<int> LogoImageID { get; set; }
        public Nullable<int> ScriptMenuID { get; set; }
        public string ScreenSize { get; set; }
        public string ScreenLayout { get; set; }
        public int ScriptSectionID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    
        public virtual ScriptImage ScriptImage { get; set; }
        public virtual ScriptMenu ScriptMenu { get; set; }
    }
}
