//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptObjectDetail
    {
        public int ScriptObjectDetailID { get; set; }
        public int ScriptObjectID { get; set; }
        public int Sequence { get; set; }
        public string ObjectDetailName { get; set; }
        public string ObjectDetailDataType { get; set; }
    
        public virtual ScriptObject ScriptObject { get; set; }
    }
}
