//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptTextHTML
    {
        public int ScriptTextHTMLID { get; set; }
        public string TextContent { get; set; }
        public string TextHTMLDesc { get; set; }
        public string TextHTMLContent { get; set; }
        public string TextHTMLAltContent { get; set; }
        public Nullable<bool> Searchable { get; set; }
        public Nullable<bool> ShowDescTooltip { get; set; }
        public string KeyWords { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string ClientID { get; set; }
    }
}
