//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptItemKey
    {
        public int ScriptItemKeyID { get; set; }
        public int ScriptItemID { get; set; }
        public string ItemKey { get; set; }
        public string ItemValue { get; set; }
        public string ClientID { get; set; }
    
        public virtual ScriptItem ScriptItem { get; set; }
    }
}
