//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public long TRANSACTION_ID { get; set; }
        public Nullable<bool> ACCEPTED { get; set; }
        public Nullable<long> LEAD_ID { get; set; }
        public Nullable<int> CAMPAIGN_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
    }
}
