//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public int URL_ID { get; set; }
        public string STATUS { get; set; }
        public string URL1 { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
    }
}
